{{- range $deploymentKey, $deploymentValue := .Values.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ index $.Values.names $deploymentKey, }}
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ index $.Values.names $deploymentKey}
  template:
    metadata:
      labels:
        app: {{ index $.Values.names $deploymentKey }}
    spec:
      {{- if index $deploymentValue containers }}
      containers:
      {{- range $containerKey, $containerValue :=  index $deploymentValue containers }}
        - name: {{ index $.Values.names $containerKey }}
          image: {{ index $.Values.images $containerKey }}

          {{- if index $deploymentValue args }}
          args:
            {{- range $argKey, $argValue :=  index $deploymentValue args }}
            - $argValue
            {{- end }}
          {{- end }}

          {{- if index $.Values.configmaps $containerKey }}
          envFrom:
            {{- range $configmapKey, $configmapValue :=  index $.Values.configmaps $containerKey }}
            - configMapRef:
                name: {{ $configmapValue.name }}
            {{- end }}
          {{- end }}

          {{- if index $.Values.secrets $containerKey }}
          env:
            {{- range $secretKey, $secretValue :=  index $.Values.secrets $containerKey }}
            - name: {{ $secretValue.varName }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretValue.valueFrom.name }}
                  key: {{ $secretValue.valueFrom.key }}
            {{- end }}
          {{- end }}

          {{- if index $.Values.persistentVolumes $containerKey }}
          volumeMounts:
            {{- range $volumeKey, $volumeValue :=  index $.Values.persistentVolumes $containerKey }}
            - mountPath: {{ $volumeValue.mountPath }}
              name: {{ $volumeValue.name }}
            {{- end }}
          {{- end }}
      {{- end }}
      {{- end }}

      {{- if index $.Values.persistentVolumes $deploymentKey }}
      volumes:
        {{- range $volumeKey, $volumeValue :=  index $.Values.persistentVolumes $deploymentKey }}
        - name: {{ $volumeValue.name }}
          persistentVolumeClaim:
            claimName: {{ $volumeValue.claimName }}
        {{- end }}
      {{- end }}
{{- end }}
