{{- range $deploymentKey, $deploymentValue := .Values.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ index $.Values.names $deploymentKey }}
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ index $.Values.names $deploymentKey }}
  template:
    metadata:
      labels:
        app: {{ index $.Values.names $deploymentKey }}
    spec:
      {{- if hasKey $deploymentValue "containers" }}
      containers:
      {{- range $containerKey, $containerValue :=  $deploymentValue.containers }}
        - name: {{ index $.Values.names $containerKey }}
          image: {{ index $.Values.images $containerKey }}


          {{- if kindIs "map" $containerValue }}
          {{- if hasKey $containerValue "args" }}
          args:
            {{- range $argKey, $argValue :=  $containerValue.args }}
            - {{ $argValue }}
            {{- end }}
          {{- end }}
          {{- end }}

          {{- if index (default dict $.Values.configmaps) $containerKey }}
          envFrom:
            {{- range $configmapKey, $configmapValue :=  index $.Values.configmaps $containerKey }}
            - configMapRef:
                name: {{ $configmapValue.name }}
            {{- end }}
          {{- end }}

          {{- if index (default dict $.Values.secrets) $containerKey }}
          env:
            {{- range $secretKey, $secretValue :=  index $.Values.secrets $containerKey }}
            - name: {{ $secretValue.varName }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretValue.valueFrom.name }}
                  key: {{ $secretValue.valueFrom.key }}
            {{- end }}
          {{- end }}

          {{- $persistentVolumeExists := index (default dict $.Values.persistentVolumes) $containerKey }}
          {{- $mountedConfigMaps := default dict (index (default dict $.Values.mountedConfigmaps) $deploymentKey) }}
          {{- $configMapExists := index $mountedConfigMaps $containerKey }}
          {{- if or $persistentVolumeExists $configMapExists }}
          volumeMounts:
            {{- if $persistentVolumeExists }}
            {{- range $volumeKey, $volumeValue :=  index $.Values.persistentVolumes $containerKey }}
            - mountPath: {{ $volumeValue.mountPath }}
              name: {{ $volumeValue.name }}
            {{- end }}
            {{- end }}

            {{- if index $mountedConfigMaps $containerKey }}
            {{- range $confiMapKey, $configmapValue :=  index $mountedConfigMaps $containerKey }}
            - mountPath: {{ $configmapValue.mountPath }}
              name: {{ $configmapValue.name }}
            {{- end }}
            {{- end }}
          {{- end }}
      {{- end }}
      {{- end }}

      {{- $persistentVolumeExists := index (default dict $.Values.persistentVolumes) $deploymentKey }}
      {{- $configMapExists := index (default dict $.Values.mountedConfigmaps) $deploymentKey }}
      {{- if or $persistentVolumeExists $configMapExists }}
      volumes:
        {{- if or $persistentVolumeExists }}
        {{- range $volumeKey, $volumeValue :=  index $.Values.persistentVolumes $deploymentKey }}
        - name: {{ $volumeValue.name }}
          persistentVolumeClaim:
            claimName: {{ $volumeValue.claimName }}
        {{- end }}
        {{- end }}

        {{- if $configMapExists }}
        {{- range $deploymentConfigmapsKey, $deploymentConfigmapsValue :=  index $.Values.mountedConfigmaps $deploymentKey }}
        {{- range $configmapKey, $configmapValue :=  $deploymentConfigmapsValue }}
        - name: {{ $configmapValue.name }}
          configMap:
            name: {{ $configmapValue.name }}
        {{- end }}
        {{- end }}
        {{- end }}
      {{- end }}
{{- end }}
